const LocalStorage = {
    USER: "USER",
    COMPANY: "COMPANY",
    COMPANY_ID: "COMPANY_ID",
    TOKEN: "TOKEN",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    SIDEBAR_ACTIVE_MENU_ITEM: "SIDEBAR_ACTIVE_MENU_ITEM",
    SETTING_ACTIVE_MENU_ITEM: "SETTING_ACTIVE_MENU_ITEM",
    REPORT_ACTIVE_MENU_ITEM: "REPORT_ACTIVE_MENU_ITEM",
};
export default LocalStorage;
